name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Bundle
        run: |
          tar -czf teknoir-ansible.tar.gz ansible.cfg ansible_system.cfg inventory.py inventory_system.py

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: teknoir-ansible.tar.gz
          generate_release_notes: true
